# enable color support of ls and also add handy aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
# some more ls aliases
alias ll='ls -alF'
alias la='ls -Al'
alias l='ls -CF'
alias cr='code -r'
alias d='docker'
alias dp='docker ps'
alias dcp='docker container prune'
alias dip='docker image prune'
alias dv='docker volume'
alias dn='docker network'
alias dl='docker logs'
alias di='docker inspect'
alias de='docker exec -it'
alias dc='docker-compose'
alias g='git'
alias cl='clear'
alias make='make --no-print-directory'
alias glogin='gcloud auth login'
alias galogin='gcloud auth application-default login'
alias gc='gcloud'
alias p='python -m colored_traceback'
